### PR TITLE
feat(readme): workflow for adding questions to app

### PR DESCRIPTION
**Pull request by Charlotteis**
This documents what each question on the app is formed of, and the best workflow for ensuring that the actual answers are displayed.

This should be the solution for #60

### CODE REVIEW

**Comment by gr2m** [comment]
looks good to me :+1:

**Comment by Charlotteis** [comment]
Would love to hear @ffffux's thoughts on whether this is a good explanation or not :)

**Comment by Charlotteis** [comment]
Anyone have any thoughts on this?

**Comment by Charlotteis** [comment]
*knock knock*

**Comment by gr2m** [comment]
oh so sorry this stayed open for so long. I say we merge it in, it’s much better than what we have right now. If there is feedback, we make follow up PRs :)

**Pull request merged**
