### PR TITLE
fix(footer): add right link to impressum

### PR DESCRIPTION
**Pull request by Charlotteis**
The original link to the impressum ends in a 404, I added a link to what I think is the right one :)

### CODE REVIEW

**Comment by gr2m** [comment]
It's not relevant for this projcet yet, but can you change the commit message to `fix(footer): ...`? Without the space after `fix`, and with a `:` after `(footer)` :)

**Comment by Charlotteis** [comment]
Sure!

**Comment by Charlotteis** [comment]
Done! @gr2m

**Comment by gr2m** [comment]
merged via 4cb3345. Not yet deployed, because my grunt fails me :/ ping @boennemann

**Pull request closed without merging**
