### PR TITLE
fix: add href to DOCS in menu

### PR DESCRIPTION
**Pull request by busyxin**
Fixes hoodiehq/hood.ie#193

### CODE REVIEW

**Comment by Charlotteis** [comment]
Thanks for this!

Your code works as intended :)

Looks like we have a failure on the testing side of things because Bower cannot find the right version of angular. I don't think this is a problem with your work though! I'll ask in our [Slack chat](http://hood.ie/chat) what the best route is to fix this bug!

**Comment by zoepage** [comment]
@boennemann didn't we fix this? https://travis-ci.org/hoodiehq/faq/builds/78372460

**Comment by boennemann** [comment]
@zoepage I fixed it on the staging repo, will apply it to this repo.

**Comment by boennemann** [comment]
https://github.com/hoodiehq/faq/commit/e8f87ed5b8a2ec7c105844bd3c96335c470a25b9

**Comment by Charlotteis** [comment]
Awesome, thanks for this @busyxin (& Zoe & Stephan!):tada:

**Comment by zoepage** [comment]
Cool, thanks @boennemann <3
I was just wondering :)

**Pull request merged**
